increase max doc length limit: 1M -> 4M
stargate/jsonapi pull request #841
Opened 2024-01-29 17:21 UTC by Yuqi-Du

document max-size 1m characters -> 4m characters 

**Which issue(s) this PR fixes**:
Fixes #817 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2024-01-29 17:41 UTC, tatu-at-datastax commented on src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java
> +    Log.error("! " + docJson.length());
These were probably left by accident, remove :)

2024-01-29 17:42 UTC, tatu-at-datastax commented on src/test/java/io/stargate/sgv2/jsonapi/service/shredding/ShredderDocLimitsTest.java
> +      // Given we fail at 4 meg, let's try 600k (8 x 5 x 7.5k)
Would be nice to try over 1 meg document to see limit is increased?

2024-01-29 17:43 UTC, tatu-at-datastax requested changes
Need to remove log statements, otherwise looks good.

2024-01-29 21:52 UTC, tatu-at-datastax approved these changes

2024-01-30 16:34 UTC, tatu-at-datastax approved these changes

2024-01-30 17:49 UTC, merged

2024-02-02 19:53 UTC, vkarpov15 reviewed
LGTM :+1: